C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Models/IngresosGastosIberoCRC.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace IngresosGastos.Models
{
    public class IngresosGastosIberoCRC
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength (60, MinimumLength =3)]
        public string Descripcion { get; set; }
        [Required]
        public bool EsIngreso { get; set; }
        [Required]
        public double Valor { get; set; }
    }
}

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace IngresosGastos.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Controllers/IngresosGastosIberoCRCsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using IngresosGastos.Data;
using IngresosGastos.Models;

namespace IngresosGastos.Controllers
{
    public class IngresosGastosIberoCRCsController : Controller
    {
        private AppDBContext db = new AppDBContext();

        // GET: IngresosGastosIberoCRCs
        public ActionResult Index()
        {
            double ingresos, gastos, neto;

            ingresos = db.IngresosGastos.Where(m => m.EsIngreso == true).Select(p => p.Valor).Sum();
            gastos = db.IngresosGastos.Where(m => m.EsIngreso == false).Select(p => p.Valor).Sum();
            neto = ingresos + gastos;
            ViewBag.Ingresos = ingresos;
            ViewBag.Gastos = gastos;
            ViewBag.neto = neto;


            return View(db.IngresosGastos.ToList());
        }

        // GET: IngresosGastosIberoCRCs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngresosGastosIberoCRC ingresosGastosIberoCRC = db.IngresosGastos.Find(id);
            if (ingresosGastosIberoCRC == null)
            {
                return HttpNotFound();
            }
            return View(ingresosGastosIberoCRC);
        }

        // GET: IngresosGastosIberoCRCs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: IngresosGastosIberoCRCs/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Descripcion,EsIngreso,Valor")] IngresosGastosIberoCRC ingresosGastosIberoCRC)
        {
            if (ModelState.IsValid)
            {
                db.IngresosGastos.Add(ingresosGastosIberoCRC);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(ingresosGastosIberoCRC);
        }

        // GET: IngresosGastosIberoCRCs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngresosGastosIberoCRC ingresosGastosIberoCRC = db.IngresosGastos.Find(id);
            if (ingresosGastosIberoCRC == null)
            {
                return HttpNotFound();
            }
            return View(ingresosGastosIberoCRC);
        }

        // POST: IngresosGastosIberoCRCs/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Descripcion,EsIngreso,Valor")] IngresosGastosIberoCRC ingresosGastosIberoCRC)
        {
            if (ModelState.IsValid)
            {
                db.Entry(ingresosGastosIberoCRC).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(ingresosGastosIberoCRC);
        }

        // GET: IngresosGastosIberoCRCs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IngresosGastosIberoCRC ingresosGastosIberoCRC = db.IngresosGastos.Find(id);
            if (ingresosGastosIberoCRC == null)
            {
                return HttpNotFound();
            }
            return View(ingresosGastosIberoCRC);
        }

        // POST: IngresosGastosIberoCRCs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            IngresosGastosIberoCRC ingresosGastosIberoCRC = db.IngresosGastos.Find(id);
            db.IngresosGastos.Remove(ingresosGastosIberoCRC);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">Aplicacion de Ingresos Gastos</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <a href="@Url.Action("Index", "IngresosGastosIberoCRCs")" class=" btn btn-block alert-link ">Menu de Ingresos Gastos</a>

</div>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/IngresosGastosIberoCRCs/Create.cshtml
@model IngresosGastos.Models.IngresosGastosIberoCRC

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IngresosGastosIberoCRC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EsIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EsIngreso)
                    @Html.ValidationMessageFor(model => model.EsIngreso, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/IngresosGastosIberoCRCs/Delete.cshtml
@model IngresosGastos.Models.IngresosGastosIberoCRC

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>IngresosGastosIberoCRC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EsIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EsIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/IngresosGastosIberoCRCs/Details.cshtml
@model IngresosGastos.Models.IngresosGastosIberoCRC

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>IngresosGastosIberoCRC</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EsIngreso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EsIngreso)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/IngresosGastosIberoCRCs/Edit.cshtml
@model IngresosGastos.Models.IngresosGastosIberoCRC

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>IngresosGastosIberoCRC</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EsIngreso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.EsIngreso)
                    @Html.ValidationMessageFor(model => model.EsIngreso, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/IngresosGastosIberoCRCs/Index.cshtml
@model IEnumerable<IngresosGastos.Models.IngresosGastosIberoCRC>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CRUD</h2>

<p>
    <a href="@Url.Action("Create", "IngresosGastosIberoCRCs")" class="btn btn-dark alert-info" >Create new</a>
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EsIngreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Valor)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descripcion)
        </td>
        <td>
            @if(item.EsIngreso == true)
                {
                <p class="text-primary"> Ingreso </p>
                }
                else
                {
                <p class="text-danger"> Gasto </p>
                }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Valor)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }, new {@class="btn btn-success"}) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }, new {@class="btn btn-info" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }, new {@class="btn btn-danger" })
        </td>
    </tr>
}

</table>

<div class="from-grup row">
    <div class="col-sm-1">
        <label class=" col-form-label text-primary">Total de ingresos</label>
    </div>
    <div class="col-sm-2 text-lg-center ">
        <label class=" col-form-label ">@ViewBag.Ingresos</label>
    </div>
</div>

<div class="from-grup row">
    <div class="col-sm-1">
        <label class=" col-form-label text-primary">Total de gastos</label>
    </div>
    <div class="col-sm-2 text-lg-center ">
        <label class=" col-form-label ">@ViewBag.Gastos</label>
    </div>
</div>

<div class="from-grup row">
    <div class="col-sm-1">
        <label class=" col-form-label text-primary">Total neto</label>
    </div>
    <div class="col-sm-2 text-lg-center ">
        <label class=" col-form-label ">@ViewBag.neto</label>
    </div>
</div>

C#/CRUD Asp.net framework/IngresosGastos/IngresosGastos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>